https://dashboard.render.com/web/srv-d8e3r3urnols739tlbh0/deploys/dep-d8e3r46rnols739tlbrg?r=2026-05-31%4013%3A53%3A24%7E2026-05-31%4013%3A56%3A51

services:
  - type: web
    name: forum-semiya
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      GIGACHAT_CLIENT_ID=019e7e12-2fd0-7cc4-8e71-486f3f488aa5
      GIGACHAT_SECRET_KEY=MDE5ZTdlMTItMmZkMC03Y2M0LThlNzEtNDg2ZjNmNDg4YWE1OjJiNmQzZWRiLTBlMzgtNGFkNC1iNWQwLThkZTgwYmFhZGVmNA==
      GIGACHAT_SCOPE=GIGACHAT_API_PERS